#!/bin/bash

java -cp language/src/main/java/com/oracle/truffle/sl/parser/antlr/antlr-4.7.2-complete.jar org.antlr.v4.Tool -package com.oracle.truffle.sl.parser -o language/src/main/java/com/oracle/truffle/sl/parser -no-listener language/src/main/java/com/oracle/truffle/sl/parser/SimpleLanguage.g4
mvn compile -f language/pom.xml